Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,4 +1,5 @@
-steps:
+
+
 
   #- name: 'gcr.io/ecommerce-434317/sonar-scanner:latest'
   #  args:
@@ -12,30 +13,20 @@ steps:
     entrypoint: npm
     args: ['install']
 
-  - name: 'ubuntu'
+    #Preparar entorno para sonar-scanner
+  - name: 'gcr.io/cloud-builders/gcloud'
     entrypoint: 'bash'
-    args: ['-c', 'mkdir /workspace/.scannerwork']
-
-  - name: 'ubuntu'
-    entrypoint: 'bash'
-    args: ['-c', 'chown 1000:1000 /workspace/.scannerwork']
-
-  - name: 'ubuntu'
-    entrypoint: 'bash'
-    args: ['-c', 'chmod -R 777 /workspace/.scannerwork']
-
-  - name: 'ubuntu'
-    entrypoint: 'bash'
-    args: ['-c', 'ls']
-
-  - name: 'ubuntu'
-    entrypoint: 'bash'
-    args: ['-c', 'ls -la /workspace']
-    
+    args:
+      - '-c'
+      - |
+        mkdir /workspace/.scannerwork
+        chown 1000:1000 /workspace/.scannerwork
+        chmod -R 777 /workspace/.scannerwork
+            
   - name: 'us-central1-docker.pkg.dev/ecommerce-434317/sonar-scanner/sonar-scanner:5'
     entrypoint: 'sonar-scanner'
     args:
-      - '-X'
+#      - '-X' #debug
       - '-Dsonar.host.url=https://sonarcloud.io'
       - '-Dsonar.projectKey=gt0593sonarcloud_basic-nodejs-app'
       - '-Dsonar.organization=gt0593sonarcloud'
@@ -45,7 +36,30 @@ steps:
   #    - '-Dsonar.tests=tests'
     env:
       - SONAR_TOKEN=2021fdd9704fb6d5378fcf9e817a873ee027bc46
-    
+
+  - name: 'gcr.io/cloud-builders/gcloud'
+    entrypoint: 'bash'
+    args:
+      - '-c'
+      - |
+        apt-get update
+        apt-get install jq -y
+        #obtener el qualitygate usando el API
+        responce =$(curl-s -u 2021fdd9704fb6d5378fcf9e817a873ee027bc46: https://sonarcloud.io/api/qualitygates/project_status?projectKey=gt0593sonarcloud_basic-nodejs-app) 
+        status =$(echo $response | jq -r '.projectStatus.status')
+        if ["$status" == "ERROR"]
+        then
+          echo "Quality Gate Failed"
+          exit 1
+        fi
+        if ["$status" == "Ok"]
+        then
+          echo "Quality Gate Passed"
+        else
+          echo "Quality Gate unknow"
+          exit 2
+        fi
+        
     # Build the container image using definition on Dockerfile
   #- name: 'gcr.io/cloud-builders/docker'
   #  args: ['build', '-t', 'us-central1-docker.pkg.dev/ecommerce-434317/basic-nodejs-app/basic-nodejs-app:$COMMIT_SHA', '.']
